### PR TITLE
delete that one botplay line, and never visit there. i was fucking traumatized

### PR DESCRIPTION
**Pull request by NAEL2XD**
i'm not joking do not visit there, it's literally bad and i just guessed it without knowing it was actually it

### CODE REVIEW

**Comment by moxie-coder** [comment]
turns out the website was hacked so this is warrant

**Comment by JordanSantiagoYT** [comment]
nael after nearly getting me into trouble by including a link to a now porn site in a jse file:

**Comment by PatoFlamejanteTV** [comment]
OMFG WHY DID I OPEN THE LINK 😭😭😭

**Comment by NAEL2XD** [comment]
> nael after nearly getting me into trouble by including a link to a now porn site in a jse file:

me when i include a link and never visited there because it would be not found

**Comment by NonsensicalGH** [comment]
The fuck.

**Comment by SyncGit12** [comment]
immediatly (sorry i forgot english) i clicked off

**Pull request merged**
