### PR TITLE
better way to support winning icon on large icons (aka 900x300, 1800x600, etc)

### PR DESCRIPTION
**Pull request by miujoan6952**

### CODE REVIEW

**Comment by miujoan6952** [comment]
i later to give some proof

**Comment by StinkTheStinker** [comment]
just do this
```
function onCreatePost()
     setProperty('iconP2.scale', scale value)
end
```

**Comment by miujoan6952** [comment]
> just do this
> 
> ```
> function onCreatePost()
>      setProperty('iconP2.scale', scale value)
> end
> ```

no i mean i fix large icon doesn't support winning icon based on some code from my fork pe 1.0

**Comment by StinkTheStinker** [comment]
> no i mean i fix large icon doesn't support winning icon based on some code from my fork pe 1.0

yeah
just make the icon the og size where it supports the winning icon, then do that

**Comment by mcagabe19** [comment]
^

**Pull request closed without merging**
