### PR TITLE
3d on haxeflixel.

### PR DESCRIPTION
**Pull request by SyncGit12**
might be needed for 3d bambi mods??

### CODE REVIEW

**Comment by StinkTheStinker** [comment]
thats probably gonna use alot of memory

**Comment by SyncGit12** [comment]
it just uses

100 mb

**Review by mcagabe19 — CHANGES_REQUESTED** [review]
looks good but I'd suggest reverting dad changes

**Comment by StinkTheStinker** [comment]
yeah

**Comment by SyncGit12** [comment]
forgor💀

**Comment by SyncGit12** [comment]
done

**Comment by mcagabe19** [comment]
there's still dad changes over here just restore them to js engine ones

**Comment by SyncGit12** [comment]
already did bruh

**Comment by mcagabe19** [comment]
image

**Comment by mcagabe19** [comment]
these shouldn't be there

**Comment by SyncGit12** [comment]
they're called "leftovers"

**Comment by SyncGit12** [comment]
hopefully ill become a contributor!...

**Review by mcagabe19 — APPROVED** [review]

**Comment by mcagabe19** [comment]
BenchmarkState should have functions properly (like it seems u can't even exit) and renamed to smth else I think other than that looks good

**Comment by SyncGit12** [comment]
im just bat at coding stuf

**Comment by SyncGit12** [comment]
also you can use the latest version of everything and js engine will compile btw

**Review by moxie-coder — APPROVED** [review]
seems good, I can add the functions myself

**Comment by SyncGit12** [comment]
https://github.com/user-attachments/assets/032cdecd-5276-4eff-9adc-11ffd0d1c52e

**Comment by mcagabe19** [comment]
@moxie-coder I'm merging this, contiune when ur available

**Comment by moxie-coder** [comment]
> @moxie-coder I'm merging this, contiune when ur available

okie

**Comment by SyncGit12** [comment]
contiune my favorite word

(no pun intended)

**Pull request merged**
