### PR TITLE
fix addWiggleEffect function not work

### PR DESCRIPTION
**Pull request by Miukothoi2011**
by replace the 2nd's arg to string and move `WiggleEffect` to `Shader.hx`

### CODE REVIEW

**Comment by JordanSantiagoYT** [comment]
it's good

but it needs a HEAT_WAVE_BOTH option otherwise some specific person might not be too happy abt it!!!!!!!!

**Comment by Miukothoi2011** [comment]
> it's good
> 
> but it needs a HEAT_WAVE_BOTH option otherwise some specific person might not be too happy abt it!!!!!!!!

here i fix

**Comment by Miukothoi2011** [comment]
oh i forgot add verticalStrength and horizontalStrength args

**Comment by Miukothoi2011** [comment]
here i add

**Comment by Miukothoi2011** [comment]
[i tested complete](https://small.fileditchstuff.me/s16/KxTTGsNndLpipRoOieG.mp4)

**Pull request merged**
